### ISSUE TITLE
请问是不是 ios 10 或者某个以上版本才可以用?

### ISSUE THREAD

**Issue by hick** [12425/wechat-exporter#3]
没有足够的版本可以验证的话, 可以麻烦确认下确认下已经验证的版本?  我的 iphone5s 的 备份里好像只有一个 Manifest.db 没有代码中的  Manifest.mbdb

thx

**Comment by hick** [comment]
稍微查了下好像是新版的 ios 还是 itunes 的调整的,  具体没经验还不大清楚

**Comment by hick** [comment]
我的 ios 是  10.3.2

**Comment by 12425** [comment]
你好，我的 iOS 版本是 9.3.5。
新版本也许可以参考 @w1ndy 的这个 [PR](/12425/wechat-exporter/pull/2/commits/8f3e0119702ad7d0afc73f69b61a2531726ac7ef)。

**Comment by 12425** [comment]
你好，现在可以解析 Manifest.db 了。
