### ISSUE TITLE
Add UTF BOM for supporting Microsoft Excel 

### ISSUE THREAD

**Issue by ajfg93** [12425/wechat-exporter#4]
Below this line:
https://github.com/12425/wechat-exporter/blob/c71fb382af370e171aa2952a902292a78bcc1495/wechat-exporter.py#L444
add `fo.write('\ufeff')`

兄弟我用Excel （好像是Office 365）打开会遇到乱码，Windows 下的Excel好像需要一个BOM，可以把这个搞成这个配置项，我加完之后再打开显示正常。

By the way, 谢谢你的script~

**Comment by 12425** [comment]
你好兄弟！
脚本生成的 csv 文件是标准格式，符合 [RFC 4180](https://tools.ietf.org/html/rfc4180)。用户可以再从这些 csv 文件写入数据库或者转成其他任意的格式。如果加了 BOM，其他工具可能会出错。
如果要以 Excel 打开，可以参考
https://stackoverflow.com/questions/6002256/#answers

**Comment by ajfg93** [comment]
啊对啊，加了BOM可能不知道其他工具怎样，但考虑到大多数人都是用Excel打开的嘛。。我就是建议这个能做成配置选项，也就几行代码的事

**Comment by 12425** [comment]
你好！现已支持这个选项了。
