### ISSUE TITLE
_parse_profile好像会死循环

### ISSUE THREAD

**Issue by li-xunhuan** [12425/wechat-exporter#5]
跑着跑着就自己停了

**Comment by li-xunhuan** [comment]
```
b'\x08\x00\x12\x02CN\x1a\tGuangdong"\x08Shenzhen*vQQ\xe5\xae\x89\xe5\x85\xa8\xe4\xb8\xad\xe5\xbf\x83\xe5\xae\x98\xe6\x96\xb9\xe5\xbe\xae\xe4\xbf\xa1\xe3\x80\x82\xe5\x8a\xaa\xe5\x8a\x9b\xe4\xbf\x9d\xe6\x8a\xa4\xe6\x82\xa8\xe7\x9a\x84QQ\xe5\xae\x89\xe5\x85\xa8\xef\xbc\x8c\xe5\x85\xb3\xe9\x94\xae\xe6\x97\xb6\xe5\x88\xbb\xe5\x8f\x8a\xe6\x97\xb6\xe6\x8f\x90\xe9\x86\x92\xef\xbc\x8c\xe9\x9a\x8f\xe6\x97\xb6\xe6\x8e\x8c\xe6\x8f\xa1\xe5\xb8\x90\xe5\x8f\xb7\xe5\xae\x89\xe5\x85\xa8\xe5\x8a\xa8\xe6\x80\x81\xe3\x80\x82'
```
比如这个就会引起死循环。

**Comment by 12425** [comment]
谢谢！已修复。
7b1413e

**Comment by li-xunhuan** [comment]
还是会解析失败，比如下面的数据

profile %x: %r 129 b'*\x9a\x01\xe5\xbf\xab\xe9\x80\x9f\xe5\x8a\x9e\xe5\x8d\xa1\xef\xbc\x8c\xe9\xa2\x9d\xe5\xba\xa6\xe6\x9c\x80\xe9\xab\x985\xe4\xb8\x87\xe5\x85\x83\xef\xbc\x9b\xe5\x85\x8d\xe8\xb4\xb9\xe5\xbc\x80\xe9\x80\x9a\xe7\xac\x94\xe7\xac\x94\xe4\xba\xa4\xe6\x98\x93\xe6\x8f\x90\xe9\x86\x92\xef\xbc\x8c\xe4\xbf\x9d\xe9\x9a\x9c\xe7\x94\xa8\xe5\x8d\xa1\xe5\xae\x89\xe5\x85\xa8\xef\xbc\x9b\xe5\xbf\xab\xe9\x80\x9f\xe6\x8f\x90\xe5\x8d\x87\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe4\xb8\x80\xe9\x94\xae\xe6\x9f\xa5\xe8\xb4\xa6\xe5\x8d\x95\xe3\x80\x81\xe6\x9f\xa5\xe7\xa7\xaf\xe5\x88\x86\xe3\x80\x81\xe5\x8a\x9e\xe5\x88\x86\xe6\x9c\x9f\xef\xbc\x81\x08\x00\x12\x02CN\x1a\x08Shanghai"\x13Pudong New District'

**Comment by li-xunhuan** [comment]
profile %x: %r 129 b'*\x9a\x01\xe5\xbf\xab\xe9\x80\x9f\xe5\x8a\x9e\xe5\x8d\xa1\xef\xbc\x8c\xe9\xa2\x9d\xe5\xba\xa6\xe6\x9c\x80\xe9\xab\x985\xe4\xb8\x87\xe5\x85\x83\xef\xbc\x9b\xe5\x85\x8d\xe8\xb4\xb9\xe5\xbc\x80\xe9\x80\x9a\xe7\xac\x94\xe7\xac\x94\xe4\xba\xa4\xe6\x98\x93\xe6\x8f\x90\xe9\x86\x92\xef\xbc\x8c\xe4\xbf\x9d\xe9\x9a\x9c\xe7\x94\xa8\xe5\x8d\xa1\xe5\xae\x89\xe5\x85\xa8\xef\xbc\x9b\xe5\xbf\xab\xe9\x80\x9f\xe6\x8f\x90\xe5\x8d\x87\xe9\xa2\x9d\xe5\xba\xa6\xef\xbc\x9b\xe4\xb8\x80\xe9\x94\xae\xe6\x9f\xa5\xe8\xb4\xa6\xe5\x8d\x95\xe3\x80\x81\xe6\x9f\xa5\xe7\xa7\xaf\xe5\x88\x86\xe3\x80\x81\xe5\x8a\x9e\xe5\x88\x86\xe6\x9c\x9f\xef\xbc\x81\x08\x00\x12\x02CN\x1a\x08Shanghai"\x13Pudong New District'

**Comment by li-xunhuan** [comment]
很奇怪，我查询出来的好友列表数据如果排除掉type=3的数据，解析就正常了！原来报错的也不报错了！

**Comment by 12425** [comment]
是因为一个我没碰到过的 `0x81`，其他的块都是 `key | size | value`，而这个和性别一样，是 `key | byte`，所以解析失败。欢迎提供更多错误信息。

**Comment by li-xunhuan** [comment]
暂时没遇到其他问题了，话说，大佬会不会解析cdn的图片消息啊？或者说怎么把聊天记录表的图片消息和本地的图片缓存关联上啊？

**Comment by 12425** [comment]
没研究过图片和视频。我个人会把重要的手动保存，其他的都会舍弃，所以不用全部导出。

**Comment by li-xunhuan** [comment]
我找到了，在本地都是用LocalMsgId关联的，图片、语音、视频都是。
